name: Validate Salesforce Metadata on PR

on:
  pull_request:
    branches: 
      - dev

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instal Node
        uses: actions/setup-node@v4
        with:
            node-version: 18

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
      
      - name: Set up JWT Private Key
        run: |
          echo "${{ secrets.SALESFORCE_JWT_KEY }}" > server.key
          chmod 600 server.key
        shell: bash

      - name: Authenticate to Salesforce Org via JWT
        run: |
          sf org login jwt \
            --client-id ${{ secrets.SALESFORCE_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SALESFORCE_USERNAME }} \
            --set-default-dev-hub \
            --alias ci-org
        shell: bash

      - name: Validate Salesforce Metadata Deployment
        run: |
          sf project deploy validate \
            --source-dir force-app \
            --target-org ci-org \
            --test-level RunLocalTests # Required for validate deployments
        shell: bash
